# Generated by Django 4.1.7 on 2023-03-13 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('product', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('price', models.CharField(max_length=100)),
                ('profit', models.CharField(max_length=100)),
                ('total', models.CharField(max_length=100)),
                ('discount', models.CharField(max_length=100)),
                ('customer', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
